name: Latest blog post workflow

on:
  schedule:
    - cron: '0 * * * *'    # hourly
  workflow_dispatch:       # manual trigger

permissions:
  contents: write          # allow pushing back to README

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # ensure ${{ github.token }} is available
          fetch-depth: 0             # avoid detached HEAD on push

      - name: Pull in posts from multiple RSS feeds
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: |
            https://feeds.feedburner.com/TheHackersNews,\
            https://krebsonsecurity.com/feed/,\
            https://www.bleepingcomputer.com/feed/
          feed_names: |
            The Hacker News,\
            Krebs on Security,\
            Bleeping Computer
          max_post_count: 25
          template: "- **$feedName**: [$title]($url) — $date$newline"
          date_format: "UTC:yyyy-mm-dd"
          readme_path: "./README.md"      # explicitly point to your README :contentReference[oaicite:1]{index=1}
          commit_message: ":robot: Update blog posts"
